name: Branch Up-to-date Check

on:
  pull_request:
    branches: [ development ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  branch-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check branch
        run: |
          git fetch
          if [ `git rev-parse HEAD` = `git rev-parse @{u}` ]; then
            echo "Branch is up to date"
          else
            echo "Branch is not up to date"
            exit 1
          fi

      - name: Set status
        uses: marvinpinto/action-automatic-rebase@v1
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
